TEMPLATE = lib
QT += core gui widgets testlib
CONFIG += c++17 staticlib
LIBS += -lhunspell
SOURCES += \
    BlockAbstract.cpp \
    BlockCppBase.cpp \
    BlockCppClass.cpp \
    BlockCppEnumeration.cpp \
    BlockCppEnumerationValue.cpp \
    BlockCppException.cpp \
    BlockCppFunction.cpp \
    BlockCppNamespace.cpp \
    BlockCppProperty.cpp \
    BlockCppQtFunction.cpp \
    BlockCppUnion.cpp \
    BlockCppVariable.cpp \
    CommandProjectAbstract.cpp \
    CommandProjectInsert.cpp \
    CommandProjectMove.cpp \
    CommandProjectRemove.cpp \
    CommandProjectSet.cpp \
    ControllerCode.cpp \
    ControllerParseAbstract.cpp \
    ControllerRouteAbstract.cpp \
    ControllerSpellingHighlight.cpp \
    ExceptionBase.cpp \
    FactoryLanguage.cpp \
    LanguageAbstract.cpp \
    LanguageCpp.cpp \
    LanguageCppQt.cpp \
    ModelMetaBlock.cpp \
    ModelMetaLanguage.cpp \
    ModelProject.cpp \
    SettingsSpelling.cpp \
    StreamBlockDir.cpp \
    StreamBlockXml.cpp \
    StreamProjectDir.cpp \
    StreamProjectXml.cpp \
    WidgetBlockAbstract.cpp \
    WidgetBlockCppBase.cpp \
    WidgetBlockCppClass.cpp \
    WidgetBlockCppEnumeration.cpp \
    WidgetBlockCppEnumerationValue.cpp \
    WidgetBlockCppException.cpp \
    WidgetBlockCppFunction.cpp \
    WidgetBlockCppNamespace.cpp \
    WidgetBlockCppProperty.cpp \
    WidgetBlockCppUnion.cpp \
    WidgetBlockCppVariable.cpp \
    WidgetDialogAbout.cpp \
    WidgetDialogCode.cpp \
    WidgetDialogOrphanFiles.cpp \
    WidgetDialogProject.cpp \
    WidgetDialogSpellingSettings.cpp \
    WidgetProject.cpp \
    WidgetStringList.cpp \
    WidgetTreeView.cpp \
    WidgetWindowMain.cpp
HEADERS += \
    Block.h \
    BlockAbstract.h \
    BlockCpp.h \
    BlockCppBase.h \
    BlockCppClass.h \
    BlockCppEnumeration.h \
    BlockCppEnumerationValue.h \
    BlockCppException.h \
    BlockCppFunction.h \
    BlockCppNamespace.h \
    BlockCppProperty.h \
    BlockCppQt.h \
    BlockCppQtFunction.h \
    BlockCppUnion.h \
    BlockCppVariable.h \
    Command.h \
    CommandProject.h \
    CommandProjectAbstract.h \
    CommandProjectInsert.h \
    CommandProjectMove.h \
    CommandProjectRemove.h \
    CommandProjectSet.h \
    Controller.h \
    ControllerCode.h \
    ControllerParse.h \
    ControllerParseAbstract.h \
    ControllerParseAbstract.t.h \
    ControllerRoute.h \
    ControllerRouteAbstract.h \
    ControllerSpellingHighlight.h \
    Exception.h \
    ExceptionBase.h \
    ExceptionBlock.h \
    ExceptionBlockLogical.h \
    ExceptionBlockRead.h \
    ExceptionBlockWrite.h \
    ExceptionProject.h \
    ExceptionProjectLogical.h \
    ExceptionProjectRead.h \
    ExceptionProjectWrite.h \
    ExceptionSystem.h \
    ExceptionSystemFile.h \
    ExceptionSystemRun.h \
    Factory.h \
    FactoryLanguage.h \
    Global.h \
    Language.h \
    LanguageAbstract.h \
    LanguageCpp.h \
    LanguageCppQt.h \
    Model.h \
    ModelMeta.h \
    ModelMetaBlock.h \
    ModelMetaLanguage.h \
    ModelProject.h \
    Settings.h \
    SettingsSpelling.h \
    Shape.h \
    ShapeRoute.h \
    Stream.h \
    StreamBlockDir.h \
    StreamBlockXml.h \
    StreamProjectDir.h \
    StreamProjectXml.h \
    Widget.h \
    WidgetBlock.h \
    WidgetBlockAbstract.h \
    WidgetBlockAbstract.t.h \
    WidgetBlockCpp.h \
    WidgetBlockCppBase.h \
    WidgetBlockCppClass.h \
    WidgetBlockCppEnumeration.h \
    WidgetBlockCppEnumerationValue.h \
    WidgetBlockCppException.h \
    WidgetBlockCppFunction.h \
    WidgetBlockCppNamespace.h \
    WidgetBlockCppProperty.h \
    WidgetBlockCppUnion.h \
    WidgetBlockCppVariable.h \
    WidgetDialog.h \
    WidgetDialogAbout.h \
    WidgetDialogCode.h \
    WidgetDialogOrphanFiles.h \
    WidgetDialogProject.h \
    WidgetDialogSpellingSettings.h \
    WidgetProject.h \
    WidgetStringList.h \
    WidgetTreeView.h \
    WidgetWindow.h \
    WidgetWindowMain.h \
    gassert.h
RESOURCES += resources.qrc
TARGET = socref
