"""
Contains the Base class.
"""
import html
from socref import abstract
from socref import edit








class Base(abstract.AbstractBlock):
    """
    This is the base block class. It implements the Socrates' Reference abstract block class. It is
    a base block class other GLSL blocks use which contains name and description properties.
    """


    #######################
    # PUBLIC - Initialize #
    #######################


    def __init__(
        self
        ):
        """
        Initializes a new base block.
        """
        abstract.AbstractBlock.__init__(self)
        self._p_name = ""
        self._p_description = ""


    ####################
    # PUBLIC - Methods #
    ####################


    def build(
        self
        ,definition
        ,begin=""
        ):
        """
        This interface is a getter method. The default implementation returns an empty list.

        Parameters
        ----------
        definition : dictionary
                     Contains scanned lines of code generated by and described in the language's
                     parser class.
        begin : string
                Added to the beginning of every line of returned source code.

        Returns
        -------
        ret0 : list
               Source code lines for this block.
        """
        return []


    def clearProperties(
        self
        ):
        """
        Implements the socref.abstract.AbstractBlock interface.
        """
        self._p_name = ""
        self._p_description = ""


    def displayName(
        self
        ):
        """
        Implements the socref.abstract.AbstractBlock interface.

        Returns
        -------
        ret0 : object
               See interface docs.
        """
        return self._p_name


    def displayView(
        self
        ):
        """
        Implements the socref.abstract.AbstractBlock interface.

        Returns
        -------
        ret0 : object
               See interface docs.
        """
        return "<h1>Description</h1><p>"+html.escape(self._p_description)+"</p>"


    def editDefinitions(
        self
        ):
        """
        Implements the socref.abstract.AbstractBlock interface.

        Returns
        -------
        ret0 : object
               See interface docs.
        """
        ret = []
        ret.append(edit.lineEdit("Name:","_p_name"))
        ret.append(edit.textEdit("Description:","_p_description",speller=True))
        return ret


    def setDefaultProperties(
        self
        ):
        """
        Implements the socref.abstract.AbstractBlock interface.
        """
        self._p_description = "Detailed description."


    #######################
    # PROTECTED - Methods #
    #######################


    def _buildChildren_(
        self
        ,definition
        ,begin=""
        ):
        """
        Getter method.

        Parameters
        ----------
        definition : dictionary
                     Scanned definitions from the old source code files.
        begin : string
                Added to the beginning of every line of returned source code.

        Returns
        -------
        ret0 : list
               Source code lines that is the combined source code of all this block's children's
               built code lines.
        """
        ret = []
        for child in self:
            ret += child.build(definition,begin)
        return ret
