"""
Contains the shader block class.
"""
import html
from PySide2 import QtGui as qtg
from socref import register
from socref import abstract
from socref import utility as ut
from . import settings








class Base(abstract.AbstractBlock):
    """
    This is the base block class. It implements the Socrates' Reference abstract block class. It is
    a base block class other GLSL blocks use which contains name and description properties.
    """


    #######################
    # PUBLIC - Initialize #
    #######################


    def __init__(self):
        """
        Initializes a new base block.
        """
        abstract.AbstractBlock.__init__(self)
        self._p_name = ""
        self._p_description = ""


    ####################
    # PUBLIC - Methods #
    ####################


    def build(self, definition, begin=""):
        """
        This interface is a getter method. The default implementation returns an empty list.

        definition : A dictionary containing scanned lines of code generated by and described in the
                     language's parser class.

        begin : An optional string that is added to the beginning of every line of returned source
                code.

        return : A list of source code lines for this block.
        """
        return []


    def clearProperties(self):
        """
        Implements the socref.abstract.AbstractBlock interface.
        """
        self._p_name = ""
        self._p_description = ""


    def displayName(self):
        """
        Implements the socref.abstract.AbstractBlock interface.

        return : See interface docs.
        """
        return self._p_name


    def displayView(self):
        """
        Implements the socref.abstract.AbstractBlock interface.

        return : See interface docs.
        """
        return "<h1>Description</h1><p>"+html.escape(self._p_description)+"</p>"


    def editDefinitions(self):
        """
        Implements the socref.abstract.AbstractBlock interface.

        return : See interface docs.
        """
        ret = []
        ret.append(ut.lineEdit("Name:","_p_name"))
        ret.append(ut.textEdit("Description:","_p_description",speller=True))
        return ret


    def setDefaultProperties(self):
        """
        Implements the socref.abstract.AbstractBlock interface.
        """
        self._p_description = "Detailed description."


    #######################
    # PROTECTED - Methods #
    #######################


    def _buildChildren_(self, definition, begin=""):
        """
        Getter method.

        definition : Scanned definitions from the old source code files.

        begin : An optional string that is appended to every line of the returned source code.

        return : A list of source code lines that is the combined source code of all this block's
                 children's built code lines.
        """
        ret = []
        for child in self:
            ret += child.build(definition,begin)
        return ret








@register("Shader")
class Shader(Base):
    """
    This is the shader block class. It implements the Socrates' Reference abstract block class. It
    represents a GLSL shader.
    """


    #######################
    # PUBLIC - Initialize #
    #######################


    def __init__(self):
        """
        Initializes a new shader block.
        """
        Base.__init__(self)
        self._p_type = "Vertex"


    ####################
    # PUBLIC - Methods #
    ####################


    def build(self, definition, begin=""):
        """
        Implements the .shader.Base interface.

        definition : See interface docs.

        begin : See interface docs.

        return : See interface docs.
        """
        ret = self._buildChildren_(definition,begin)
        ret += [""]*settings.H1LINES + ["void main()","{","}"]
        return ret


    def buildList(self):
        """
        Implements the socref.abstract.AbstractBlock interface.

        return : See interface docs.
        """
        return ("Variable","Structure","Function")


    def clearProperties(self):
        """
        Implements the socref.abstract.AbstractBlock interface.
        """
        Base.clearProperties(self)
        self._p_type = "Vertex"


    def displayView(self):
        """
        Implements the socref.abstract.AbstractBlock interface.

        return : See interface docs.
        """
        type_ = "<h2>Type</h2><p>"+html.escape(self._p_type)+"</p>"
        return Base.displayView(self)+type_


    def editDefinitions(self):
        """
        Implements the socref.abstract.AbstractBlock interface.

        return : See interface docs.
        """
        ret = Base.editDefinitions(self)
        combo = ut.comboEdit("Type:","_p_type")
        ut.addComboSelect(combo,"Vertex",qtg.QIcon(":/glsl/vertex_shader.svg"))
        ut.addComboSelect(combo,"Fragment",qtg.QIcon(":/glsl/fragment_shader.svg"))
        ut.addComboSelect(combo,"Tesselation Control",qtg.QIcon(":/glsl/tesselation_shader.svg"))
        ut.addComboSelect(combo,"Tesselation Evaluation",qtg.QIcon(":/glsl/tesselation_shader.svg"))
        ut.addComboSelect(combo,"Geometry",qtg.QIcon(":/glsl/geometry_shader.svg"))
        ut.addComboSelect(combo,"Compute",qtg.QIcon(":/glsl/compute_shader.svg"))
        ret.append(combo)
        return ret


    def extension(self):
        """
        Getter method.

        return : A file extension string based off this shader's type.
        """
        if self._p_type == "Vertex":
            return settings.VERTEX_EXTENSION
        elif self._p_type == "Fragment":
            return settings.FRAGMENT_EXTENSION
        elif self._p_type == "Tesselation Control":
            return settings.TESS_CTRL_EXTENSION
        elif self._p_type == "Tesselation Evaluation":
            return settings.TESS_EVAL_EXTENSION
        elif self._p_type == "Geometry":
            return settings.GEOMETRY_EXTENSION
        elif self._p_type == "Compute":
            return settings.COMPUTE_EXTENSION
        else:
            raise RuntimeError("Shader is invalid type.")


    def icon(self):
        """
        Implements the socref.abstract.AbstractBlock interface.

        return : See interface docs.
        """
        if self._p_type == "Vertex":
            return qtg.QIcon(":/glsl/vertex_shader.svg")
        elif self._p_type == "Fragment":
            return qtg.QIcon(":/glsl/fragment_shader.svg")
        elif self._p_type.startswith("Tesselation"):
            return qtg.QIcon(":/glsl/tesselation_shader.svg")
        elif self._p_type == "Geometry":
            return qtg.QIcon(":/glsl/geometry_shader.svg")
        elif self._p_type == "Compute":
            return qtg.QIcon(":/glsl/compute_shader.svg")
        else:
            raise RuntimeError("Shader is invalid type.")


    def setDefaultProperties(self):
        """
        Implements the socref.abstract.AbstractBlock interface.
        """
        Base.setDefaultProperties(self)
        self._p_name = "shader"
        self._p_type = "Vertex"
