"""
Contains the Package class.
"""
import html
from PySide2 import QtGui as qtg
from socref import abstract
from socref import public as scr
from . import parser
from . import settings








@scr.register("Package",root=True)
class Package(abstract.AbstractBlock):
    """
    This is the package block class. It implements the Socrates' Reference
    abstract block class. It represents a python package. It is the root block
    type of a python project. It implements one additional interface method used
    by other block definitions of the python language.
    """


    def __init__(
        self
        ):
        """
        Initializes a new package block.
        """
        super().__init__()
        self._p_name = ""
        self._p_description = ""


    def build(
        self
        ,definition
        ,begin=""
        ):
        """
        This interface is a getter method. The default implementation returns an
        empty list.

        Parameters
        ----------
        definition : dictionary
                     Scanned lines of code generated by and described in the
                     language's parser class.
        begin : string
                Added to the beginning of every line of returned source code.

        Returns
        -------
        ret0 : list
               Source code lines for this block.
        """
        (header,footer) = Package._build_(self,definition,begin)
        return header+self._buildChildren_(definition,begin)+footer


    def buildList(
        self
        ):
        """
        Implements the socref.abstract.AbstractBlock interface.

        Returns
        -------
        ret0 : object
               See interface docs.
        """
        if self.parent() is None:
            return ("Package","Module","Class")
        else:
            return ("Package","Module","Class","Function")


    def clearProperties(
        self
        ):
        """
        Implements the socref.abstract.AbstractBlock interface.
        """
        self._p_name = ""
        self._p_description = ""


    def displayName(
        self
        ):
        """
        Implements the socref.abstract.AbstractBlock interface.

        Returns
        -------
        ret0 : object
               See interface docs.
        """
        return self._p_name


    def displayView(
        self
        ):
        """
        Implements the socref.abstract.AbstractBlock interface.

        Returns
        -------
        ret0 : object
               See interface docs.
        """
        return scr.richTextBlocks(1,"Description",html.escape(self._p_description))


    def editDefinitions(
        self
        ):
        """
        Implements the socref.abstract.AbstractBlock interface.

        Returns
        -------
        ret0 : object
               See interface docs.
        """
        ret = []
        ret.append(scr.lineEdit("Name:","_p_name"))
        ret.append(scr.textEdit("Description:","_p_description",speller=True))
        return ret


    def icon(
        self
        ):
        """
        Implements the socref.abstract.AbstractBlock interface.

        Returns
        -------
        ret0 : object
               See interface docs.
        """
        return qtg.QIcon(":/python/package.svg")


    def parser(
        self
        ):
        """
        Implements the socref.abstract.AbstractBlock interface.

        Returns
        -------
        ret0 : object
               See interface docs.
        """
        return parser.Parser(self)


    def setDefaultProperties(
        self
        ):
        """
        Implements the socref.abstract.AbstractBlock interface.
        """
        self._p_name = "package"
        self._p_description = "Detailed description."


    def _build_(
        self
        ,definition
        ,begin=""
        ,description=None
        ):
        """
        Getter method.

        Parameters
        ----------
        definition : dictionary
                     Scanned lines of code generated by and described in the
                     language's parser class.
        begin : string
                Added to the beginning of every line of returned source code.
        description : string
                      If this is not set to none then this overrides the
                      description of this block, using this given description
                      instead.

        Returns
        -------
        ret0 : list
               Import code lines for this block.
        ret1 : list
               Script code lines for this block.
        """
        if description is None:
            description = self._p_description
        header = definition.pop("pre")
        header.append('"""')
        header += scr.wrapBlocks(description,columns=settings.COLUMNS)
        header.append('"""')
        header += definition.pop("header")
        footer = []
        script = definition.pop("script")
        if script:
            footer += [""]*settings.H1LINES + script
        return (header,footer)


    def _buildChildren_(
        self
        ,definition
        ,begin=""
        ):
        """
        Getter method.

        Parameters
        ----------
        definition : dictionary
                     Scanned definitions from the old source code files.
        begin : string
                An indent that is appended to every line of the returned source
                code.

        Returns
        -------
        ret0 : list
               Source code lines that is the combined source code of all this
               block's children's built code lines, excluding any classes.
        ret1 : list
               Source code import lines that import any classes within this
               module that is created in its own special module file.
        """
        ret = []
        for block in self:
            if block._TYPE_== "Module" or block._TYPE_ == "Package":
                continue
            elif block._TYPE_ != "Class":
                ret += block.build(definition,begin)
            elif block.isInfile():
                ret += block.build(definition,begin)
        return ret
