"""
Contains the Base class.
"""
import html
from socref import abstract
from socref import edit
from socref import register
from . import settings








class Base(abstract.AbstractBlock):
    """
    This is the base block class. It implements the Socrates' Reference abstract block class. It is
    a base block class the many other C++ blocks use which contains name and description properties.
    """


    #######################
    # PUBLIC - Initialize #
    #######################


    def __init__(
        self
        ):
        """
        Initializes a new base block.
        """
        abstract.AbstractBlock.__init__(self)
        self._p_name = ""
        self._p_description = ""


    ####################
    # PUBLIC - Methods #
    ####################


    def buildDeclaration(
        self
        ,begin
        ):
        """
        This interface is a getter method. The default implementation returns an empty list.

        Parameters
        ----------
        begin : string
                Added to the beginning of each returned line of declaration code.

        Returns
        -------
        ret0 : list
               Source code lines that is the declaration of this block.
        """
        return []


    def buildDefinition(
        self
        ,definitions
        ,scope
        ,template
        ,header
        ):
        """
        This interface is a getter method. The default implementation returns a tuple with two empty
        lists.

        Parameters
        ----------
        definitions : dictionary
                      Scanned lines of code generated by and described in the language's parser
                      class.
        scope : string
                The scope for this block, not including the final double colon characters.
        template : string
                   Any template declarations that this block is within.
        header : bool
                 True if the returned definitions are for a header file or false if it is for a
                 source file.

        Returns
        -------
        ret0 : list
               Source code lines of variable definitions.
        ret1 : list
               Source code lines of function definitions.
        """
        return ([],[])


    def buildHeader(
        self
        ,definitions
        ,path
        ):
        """
        This interface is a getter method. The default implementation returns an empty list.

        Parameters
        ----------
        definitions : dictionary
                      Scanned lines of code generated by and described in the language's parser
                      class.
        path : string
               The writing path to the C++ header file of the returned lines of code.

        Returns
        -------
        ret0 : list
               Source code lines that is the entire header file this block represents. If this block
               does not represent a header file then an empty list is returned.
        """
        return []


    def buildSource(
        self
        ,definitions
        ,path
        ):
        """
        This interface is a getter method. The default implementation returns an empty list.

        Parameters
        ----------
        definitions : dictionary
                      Scanned lines of code generated by and described in the language's parser
                      class.
        path : string
               The writing path to the C++ source file of the returned lines of code.

        Returns
        -------
        ret0 : list
               Source code lines that is the entire source file this block represents. If this block
               does not represent a source file then an empty list is returned.
        """
        return []


    def clearProperties(
        self
        ):
        """
        Implements the socref.abstract.AbstractBlock interface.
        """
        self._p_name = ""
        self._p_description = ""


    def displayName(
        self
        ):
        """
        Implements the socref.abstract.AbstractBlock interface.

        Returns
        -------
        ret0 : object
               See interface docs.
        """
        return self._p_name


    def displayView(
        self
        ):
        """
        Implements the socref.abstract.AbstractBlock interface.

        Returns
        -------
        ret0 : object
               See interface docs.
        """
        return edit.richTextBlocks(1,"Description",html.escape(self._p_description))


    def editDefinitions(
        self
        ):
        """
        Implements the socref.abstract.AbstractBlock interface.

        Returns
        -------
        ret0 : object
               See interface docs.
        """
        ret = []
        ret.append(edit.lineEdit("Name:","_p_name"))
        ret.append(edit.textEdit("Description:","_p_description",speller=True))
        return ret


    def setDefaultProperties(
        self
        ):
        """
        Implements the socref.abstract.AbstractBlock interface.
        """
        self._p_description = "Detailed description."


    #######################
    # PROTECTED - Methods #
    #######################


    def _buildHeaderGuard_(
        self
        ):
        """
        Getter method.

        Returns
        -------
        ret0 : list
               Two lines that is the special header guard for this block's C++ header file.
        """
        names = []
        up = self
        while up is not None:
            if (
                up._TYPE_ == "Class"
                or (up._TYPE_ == "Namespace" and up.parent())
            ):
                names.append(up._p_name.upper())
            up = up.parent()
        names.reverse()
        guard = "_".join(names) + "_H"
        return ["#ifndef " + guard,"#define " + guard]


    def _buildNamespaces_(
        self
        ,body
        ,commentLast=False
        ):
        """
        Getter method.

        Parameters
        ----------
        body : list
               Code lines returned with wrapped namespace declarations.
        commentLast : bool
                      True to add a description comment header to the last inner most namespace or
                      false for no comments.

        Returns
        -------
        ret0 : list
               Source code lines of the given body wrapped in enclosing lines of namespace
               declarations composed from this block's parent namespace blocks.
        """
        ret = []
        namespaces = []
        up = self
        while up is not None:
            if up._TYPE_ == "Namespace" and up.parent():
                namespaces.append(up)
            up = up.parent()
        namespaces.reverse()
        if namespaces:
            last = namespaces.pop()
            ret.append("")
            for namespace in namespaces:
                ret += ["namespace "+namespace._p_name,"{"]
            if commentLast:
                ret += ["/*"]
                ret += edit.wrapBlocks(last._p_description," * ",columns=settings.COLUMNS)
                ret += [" */"]
            ret += ["namespace "+last._p_name,"{"]
            namespaces.append(last)
        ret += body
        if namespaces:
            ret += [""] + ["}"]*len(namespaces)
        return ret
