"""
Contains the namespace and generic base block classes.
"""
import html
from PySide2 import QtGui as qtg
from socref import register
from socref import utility as ut
from socref import abstract
from . import settings
from . import parser








class Base(abstract.AbstractBlock):
    """
    This is the base block class. It implements the Socrates' Reference abstract block class. It is
    a base block class the many other C++ blocks use which contains name and description properties.
    """


    #######################
    # PUBLIC - Initialize #
    #######################


    def __init__(self):
        """
        Initializes a new base block.
        """
        abstract.AbstractBlock.__init__(self)
        self._p_name = ""
        self._p_description = ""


    ####################
    # PUBLIC - Methods #
    ####################


    def buildDeclaration(self, begin):
        """
        This interface is a getter method. The default implementation returns an empty list.

        begin : A string that is added to the beginning of each returned line of declaration code.

        return : A list of source code lines that is the declaration of this block.
        """
        return []


    def buildDefinition(self, definitions, scope, template, header):
        """
        This interface is a getter method. The default implementation returns a tuple with two empty
        lists.

        definitions : A dictionary containing scanned lines of code generated by and described in
                      the language's parser class.

        scope : A string that is the scope for this block, not including the final double colon
                characters.

        template : A string that is any template declarations that this block is within.

        header : True if the returned definitions are for a header file or false if it is for a
                 source file.

        return : A tuple containing two lists of source code definitions for this block. The first
                 is variable definitions. The second is function definitions.
        """
        return ([],[])


    def buildHeader(self, definitions, path):
        """
        This interface is a getter method. The default implementation returns an empty list.

        definitions : A dictionary containing scanned lines of code generated by and described in
                      the language's parser class.

        path : The writing path to the C++ header file of the returned lines of code.

        return : A list of source code lines that is the entire header file this block represents.
                 If this block does not represent a header file then an empty list is returned.
        """
        return []


    def buildSource(self, definitions, path):
        """
        This interface is a getter method. The default implementation returns an empty list.

        definitions : A dictionary containing scanned lines of code generated by and described in
                      the language's parser class.

        path : The writing path to the C++ source file of the returned lines of code.

        return : A list of source code lines that is the entire source file this block represents.
                 If this block does not represent a source file then an empty list is returned.
        """
        return []


    def clearProperties(self):
        """
        Implements the socref.abstract.AbstractBlock interface.
        """
        self._p_name = ""
        self._p_description = ""


    def displayName(self):
        """
        Implements the socref.abstract.AbstractBlock interface.

        return : See interface docs.
        """
        return self._p_name


    def displayView(self):
        """
        Implements the socref.abstract.AbstractBlock interface.

        return : See interface docs.
        """
        return ut.richTextBlocks(1,"Description",html.escape(self._p_description))


    def editDefinitions(self):
        """
        Implements the socref.abstract.AbstractBlock interface.

        return : See interface docs.
        """
        ret = []
        ret.append(ut.lineEdit("Name:","_p_name"))
        ret.append(ut.textEdit("Description:","_p_description",speller=True))
        return ret


    def setDefaultProperties(self):
        """
        Implements the socref.abstract.AbstractBlock interface.
        """
        self._p_description = "Detailed description."


    #######################
    # PROTECTED - Methods #
    #######################


    def _buildHeaderGuard_(self):
        """
        Getter method.

        return : A list of two lines that is the special header guard for this block's C++ header
                 file.
        """
        names = []
        up = self
        while up is not None:
            if (
                up._TYPE_ == "Class"
                or (up._TYPE_ == "Namespace" and up.parent())
            ):
                names.append(up._p_name.upper())
            up = up.parent()
        names.reverse()
        guard = "_".join(names) + "_H"
        return ["#ifndef " + guard,"#define " + guard]


    def _buildNamespaces_(self, body, commentLast=False):
        """
        Getter method.

        body : A list of code lines returned with wrapped namespace declarations.

        commentLast : True to add a description comment header to the last inner most namespace or
                      false for no comments.

        return : A list of source code lines of the given body wrapped in enclosing lines of
                 namespace declarations composed from this block's parent namespace blocks.
        """
        ret = []
        namespaces = []
        up = self
        while up is not None:
            if up._TYPE_ == "Namespace" and up.parent():
                namespaces.append(up)
            up = up.parent()
        namespaces.reverse()
        if namespaces:
            last = namespaces.pop()
            ret.append("")
            for namespace in namespaces:
                ret += ["namespace "+namespace._p_name,"{"]
            if commentLast:
                ret += ["/*"]
                ret += ut.wrapBlocks(last._p_description," * ",columns=settings.COLUMNS)
                ret += [" */"]
            ret += ["namespace "+last._p_name,"{"]
            namespaces.append(last)
        ret += body
        if namespaces:
            ret += [""] + ["}"]*len(namespaces)
        return ret








@register("Namespace",root=True)
class Namespace(Base):
    """
    This is the namespace block class. It implements the Socrates' Reference abstract block class.
    It represents a C++ namespace. It is the root block type of a C++ project.
    """


    #######################
    # PUBLIC - Initialize #
    #######################


    def __init__(self):
        """
        Initializes a new namespace block.
        """
        Base.__init__(self)
        self._p_hidden = "0"


    ####################
    # PUBLIC - Methods #
    ####################


    def buildDeclaration(self, begin):
        """
        Implements the .namespace.Base interface.

        begin : See interface docs.

        return : See interface docs.
        """
        forwards = []
        ret = []
        for child in self:
            if child._TYPE_ == "Class":
                forwards += child.buildForward()
            else:
                ret += child.buildDeclaration(begin)
        if forwards:
            ret += [""]*settings.H2LINES
        ret += forwards
        return ret


    def buildDefinition(self, definitions, scope, template, header):
        """
        Implements the .namespace.Base interface.

        definitions : See interface docs.

        scope : See interface docs.

        template : See interface docs.

        header : See interface docs.

        return : See interface docs.
        """
        variables = []
        functions = []
        for child in self:
            if child._TYPE_ != "Class":
                (v,f) = child.buildDefinition(definitions,scope,template,header)
                variables += v
                functions += f
        return (variables,functions)


    def buildHeader(self, definitions, path):
        """
        Implements the .namespace.Base interface.

        definitions : See interface docs.

        path : See interface docs.

        return : See interface docs.
        """
        ret = self._buildHeaderGuard_()
        ret += definitions["headers"].get(path,[])
        body = self.buildDeclaration("")
        (variables,functions) = self.buildDefinition(definitions,"","",True)
        if variables:
            body += [""]*settings.H1LINES
        body += variables+functions
        ret += self._buildNamespaces_(body,self._TYPE_ == "Namespace")
        ret += ["","#endif"]
        return ret


    def buildList(self):
        """
        Implements the socref.abstract.AbstractBlock interface.

        return : See interface docs.
        """
        return ("Namespace","Enumeration","Variable","Function","Class","Union")


    def buildSource(self, definitions, path):
        """
        Implements the .namespace.Base interface.

        definitions : See interface docs.

        path : See interface docs.

        return : See interface docs.
        """
        ret = definitions["headers"].get(path,[])
        body = []
        (variables,functions) = self.buildDefinition(definitions,"","",False)
        if variables:
            body += [""]*settings.H1LINES
        body += variables+functions
        ret += self._buildNamespaces_(body)
        return ret


    def clearProperties(self):
        """
        Implements the socref.abstract.AbstractBlock interface.
        """
        Base.clearProperties(self)
        self._p_hidden = "0"


    def editDefinitions(self):
        """
        Implements the socref.abstract.AbstractBlock interface.

        return : See interface docs.
        """
        ret = Base.editDefinitions(self)
        ret.append(ut.checkboxEdit("Hidden","_p_hidden"))
        return ret


    def hasFunctions(self):
        """
        Getter method.

        return : True if this namespace has one or more functions or false otherwise.
        """
        for child in self:
            if child._TYPE_ == "Function":
                return True
        return False


    def icon(self):
        """
        Implements the socref.abstract.AbstractBlock interface.

        return : See interface docs.
        """
        if self.isHidden():
            return qtg.QIcon(":/cpp/hidden_namespace.svg")
        else:
            return qtg.QIcon(":/cpp/namespace.svg")


    def isHidden(self):
        """
        Getter method.

        return : True if this is a hidden namespace that must not have its name added to the scoping
                 of source code files nor have its own header or source file. If this is a regular
                 visible namespace then false is returned.
        """
        return bool(int(self._p_hidden))


    def parser(self):
        """
        Implements the socref.abstract.AbstractBlock interface.

        return : See interface docs.
        """
        return parser.Parser(self)


    def setDefaultProperties(self):
        """
        Implements the socref.abstract.AbstractBlock interface.
        """
        Base.setDefaultProperties(self)
        self._p_name = "namespace"
        self._p_hidden = "0"
